using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Text;

namespace DiagnosticsToolkit.Generators;

/// <summary>
/// Roslyn source generator for [RuntimeMetricsCollector] attribute.
/// Generates runtime diagnostics collection methods for decorated classes.
/// </summary>
[Generator]
public class RuntimeMetricsCollectorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit the attribute definition
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("RuntimeMetricsCollectorAttribute.g.cs", GetAttributeSource());
        });

        // Find classes with [RuntimeMetricsCollector] attribute
        var classesWithAttr = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax c &&
                    c.AttributeLists.Any(al => al.Attributes.Any(a =>
                        a.Name.ToString().Contains("RuntimeMetricsCollector"))),
                transform: (ctx, _) => ExtractClass(ctx))
            .Where(c => c != null!);

        // Generate runtime metrics collector for each class
        context.RegisterSourceOutput(classesWithAttr, (spc, classInfo) =>
        {
            if (classInfo != null)
            {
                var source = GenerateRuntimeMetricsCollector(classInfo);
                var fileName = $"{classInfo.ClassName}.RuntimeMetrics.g.cs";
                spc.AddSource(fileName, source);
            }
        });
    }

    private static ClassInfo? ExtractClass(GeneratorSyntaxContext ctx)
    {
        var classDecl = ctx.Node as ClassDeclarationSyntax;
        if (classDecl == null)
            return null;

        var ns = GetNamespace(classDecl);
        return new ClassInfo
        {
            Namespace = ns,
            ClassName = classDecl.Identifier.Text,
            IsPartial = classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword))
        };
    }

    private static string GetNamespace(SyntaxNode node)
    {
        foreach (var parent in node.Ancestors())
        {
            if (parent is NamespaceDeclarationSyntax ns)
                return ns.Name.ToString();
            if (parent is FileScopedNamespaceDeclarationSyntax fns)
                return fns.Name.ToString();
        }
        return "GeneratedCode";
    }

    private static string GetAttributeSource()
    {
        return @"using System;

namespace DiagnosticsToolkit.Generators;

/// <summary>
/// Marks a partial class for runtime diagnostics metrics collection generation.
/// Generates methods to collect CPU, GC, Memory, and ThreadPool metrics.
/// </summary>
[AttributeUsage(AttributeTargets.Class)]
public sealed class RuntimeMetricsCollectorAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the collection interval in milliseconds for automatic background collection.
    /// Set to 0 to disable automatic collection (manual only).
    /// </summary>
    public int IntervalMs { get; set; } = 0;

    /// <summary>
    /// Gets or sets the category name for metrics.
    /// </summary>
    public string Category { get; set; } = ""RuntimeMetrics"";
}
";
    }

    private static string GenerateRuntimeMetricsCollector(ClassInfo classInfo)
    {
        var sb = new StringBuilder();
        var ns = classInfo.Namespace != "GeneratedCode" ? classInfo.Namespace : "DiagnosticsToolkit.Generators.Sample";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using DiagnosticsToolkit.Models;");
        sb.AppendLine("using DiagnosticsToolkit.Providers;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Auto-generated runtime metrics collector for {classInfo.ClassName}");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public partial class {classInfo.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly IRuntimeMetricsProvider _metricsProvider = RuntimeMetricsProviderFactory.Create();");
        sb.AppendLine("    private static CpuUsage _lastCpuUsage;");
        sb.AppendLine("    private static MemorySnapshot _lastMemorySnapshot;");
        sb.AppendLine("    private static GcStats _lastGcStats;");
        sb.AppendLine("    private static ThreadPoolStats _lastThreadPoolStats;");
        sb.AppendLine("    private static long _lastCollectionTicks = DateTime.UtcNow.Ticks;");
        sb.AppendLine("    private static Timer? _autoCollectionTimer;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Collects current runtime metrics snapshot.</summary>");
        sb.AppendLine("    public static async Task CollectMetricsAsync()");
        sb.AppendLine("    {");
        sb.AppendLine("        _lastCpuUsage = await _metricsProvider.GetCpuUsageAsync();");
        sb.AppendLine("        _lastMemorySnapshot = await _metricsProvider.GetMemorySnapshotAsync();");
        sb.AppendLine("        _lastGcStats = await _metricsProvider.GetGcStatsAsync();");
        sb.AppendLine("        _lastThreadPoolStats = await _metricsProvider.GetThreadPoolStatsAsync();");
        sb.AppendLine("        Interlocked.Exchange(ref _lastCollectionTicks, DateTime.UtcNow.Ticks);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the last collected CPU usage metrics.</summary>");
        sb.AppendLine("    public static CpuUsage GetLastCpuUsage() => _lastCpuUsage;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the last collected memory snapshot.</summary>");
        sb.AppendLine("    public static MemorySnapshot GetLastMemorySnapshot() => _lastMemorySnapshot;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the last collected GC statistics.</summary>");
        sb.AppendLine("    public static GcStats GetLastGcStats() => _lastGcStats;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the last collected thread pool statistics.</summary>");
        sb.AppendLine("    public static ThreadPoolStats GetLastThreadPoolStats() => _lastThreadPoolStats;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets time since last metrics collection.</summary>");
        sb.AppendLine("    public static TimeSpan TimeSinceLastCollection() =>");
        sb.AppendLine("        TimeSpan.FromTicks(DateTime.UtcNow.Ticks - Interlocked.Read(ref _lastCollectionTicks));");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Starts automatic background metrics collection.</summary>");
        sb.AppendLine("    /// <param name=\"intervalMs\">Collection interval in milliseconds.</param>");
        sb.AppendLine("    public static void StartAutoCollection(int intervalMs = 5000)");
        sb.AppendLine("    {");
        sb.AppendLine("        StopAutoCollection();");
        sb.AppendLine("        _autoCollectionTimer = new Timer(async _ => await CollectMetricsAsync(),");
        sb.AppendLine("            null, TimeSpan.Zero, TimeSpan.FromMilliseconds(intervalMs));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Stops automatic background metrics collection.</summary>");
        sb.AppendLine("    public static void StopAutoCollection()");
        sb.AppendLine("    {");
        sb.AppendLine("        _autoCollectionTimer?.Dispose();");
        sb.AppendLine("        _autoCollectionTimer = null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets all current runtime metrics in one snapshot.</summary>");
        sb.AppendLine("    public static async Task<RuntimeMetricsSnapshot> GetCurrentSnapshotAsync()");
        sb.AppendLine("    {");
        sb.AppendLine("        await CollectMetricsAsync();");
        sb.AppendLine("        return new RuntimeMetricsSnapshot");
        sb.AppendLine("        {");
        sb.AppendLine("            CpuUsage = _lastCpuUsage,");
        sb.AppendLine("            Memory = _lastMemorySnapshot,");
        sb.AppendLine("            Gc = _lastGcStats,");
        sb.AppendLine("            ThreadPool = _lastThreadPoolStats,");
        sb.AppendLine("            Timestamp = DateTime.UtcNow");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Complete runtime metrics snapshot.</summary>");
        sb.AppendLine("public class RuntimeMetricsSnapshot");
        sb.AppendLine("{");
        sb.AppendLine("    public CpuUsage CpuUsage { get; set; }");
        sb.AppendLine("    public MemorySnapshot Memory { get; set; }");
        sb.AppendLine("    public GcStats Gc { get; set; }");
        sb.AppendLine("    public ThreadPoolStats ThreadPool { get; set; }");
        sb.AppendLine("    public DateTime Timestamp { get; set; }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class ClassInfo
    {
        public string Namespace { get; set; } = string.Empty;
        public string ClassName { get; set; } = string.Empty;
        public bool IsPartial { get; set; }
    }
}
